[2022-08-09 08:04:29,816] {processor.py:163} INFO - Started process (PID=38) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:04:29,825] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:04:29,827] {logging_mixin.py:109} INFO - [2022-08-09 08:04:29,826] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:04:33,121] {logging_mixin.py:109} INFO - [2022-08-09 08:04:33,115] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:04:33,160] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:04:33,193] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 3.399 seconds
[2022-08-09 08:05:03,865] {processor.py:163} INFO - Started process (PID=115) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:03,868] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:05:03,873] {logging_mixin.py:109} INFO - [2022-08-09 08:05:03,873] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:04,613] {logging_mixin.py:109} INFO - [2022-08-09 08:05:04,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:05:04,629] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:04,638] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.780 seconds
[2022-08-09 08:05:35,567] {processor.py:163} INFO - Started process (PID=177) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:35,569] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:05:35,571] {logging_mixin.py:109} INFO - [2022-08-09 08:05:35,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:36,266] {logging_mixin.py:109} INFO - [2022-08-09 08:05:36,263] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:05:36,285] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:05:36,294] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.730 seconds
[2022-08-09 08:06:06,428] {processor.py:163} INFO - Started process (PID=248) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:06,436] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:06:06,437] {logging_mixin.py:109} INFO - [2022-08-09 08:06:06,437] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:07,144] {logging_mixin.py:109} INFO - [2022-08-09 08:06:07,141] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:06:07,163] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:07,177] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.752 seconds
[2022-08-09 08:06:37,572] {processor.py:163} INFO - Started process (PID=308) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:37,575] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:06:37,577] {logging_mixin.py:109} INFO - [2022-08-09 08:06:37,577] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:38,364] {logging_mixin.py:109} INFO - [2022-08-09 08:06:38,362] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:06:38,387] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:06:38,399] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.834 seconds
[2022-08-09 08:07:09,209] {processor.py:163} INFO - Started process (PID=381) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:09,211] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:07:09,213] {logging_mixin.py:109} INFO - [2022-08-09 08:07:09,213] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:09,878] {logging_mixin.py:109} INFO - [2022-08-09 08:07:09,876] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:07:09,891] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:09,900] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.694 seconds
[2022-08-09 08:07:39,945] {processor.py:163} INFO - Started process (PID=444) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:39,947] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:07:39,949] {logging_mixin.py:109} INFO - [2022-08-09 08:07:39,949] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:40,823] {logging_mixin.py:109} INFO - [2022-08-09 08:07:40,820] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:07:40,842] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:07:40,850] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.909 seconds
[2022-08-09 08:08:10,912] {processor.py:163} INFO - Started process (PID=520) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:10,915] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:08:10,917] {logging_mixin.py:109} INFO - [2022-08-09 08:08:10,917] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:11,614] {logging_mixin.py:109} INFO - [2022-08-09 08:08:11,611] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:08:11,629] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:11,636] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.731 seconds
[2022-08-09 08:08:41,847] {processor.py:163} INFO - Started process (PID=582) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:41,849] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:08:41,850] {logging_mixin.py:109} INFO - [2022-08-09 08:08:41,850] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:42,563] {logging_mixin.py:109} INFO - [2022-08-09 08:08:42,561] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:08:42,579] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:08:42,587] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.744 seconds
[2022-08-09 08:09:12,942] {processor.py:163} INFO - Started process (PID=653) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:12,944] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:09:12,946] {logging_mixin.py:109} INFO - [2022-08-09 08:09:12,946] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:13,684] {logging_mixin.py:109} INFO - [2022-08-09 08:09:13,680] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:09:13,699] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:13,707] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.768 seconds
[2022-08-09 08:09:43,938] {processor.py:163} INFO - Started process (PID=714) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:43,941] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:09:43,942] {logging_mixin.py:109} INFO - [2022-08-09 08:09:43,942] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:44,590] {logging_mixin.py:109} INFO - [2022-08-09 08:09:44,587] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:09:44,605] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:09:44,614] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.679 seconds
[2022-08-09 08:10:15,426] {processor.py:163} INFO - Started process (PID=784) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:15,429] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:10:15,431] {logging_mixin.py:109} INFO - [2022-08-09 08:10:15,430] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:16,073] {logging_mixin.py:109} INFO - [2022-08-09 08:10:16,071] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:10:16,090] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:16,102] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.701 seconds
[2022-08-09 08:10:46,259] {processor.py:163} INFO - Started process (PID=845) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:46,263] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:10:46,265] {logging_mixin.py:109} INFO - [2022-08-09 08:10:46,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:46,933] {logging_mixin.py:109} INFO - [2022-08-09 08:10:46,930] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:10:46,948] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:10:46,957] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.703 seconds
[2022-08-09 08:11:17,373] {processor.py:163} INFO - Started process (PID=915) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:17,375] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:11:17,377] {logging_mixin.py:109} INFO - [2022-08-09 08:11:17,377] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:18,194] {logging_mixin.py:109} INFO - [2022-08-09 08:11:18,192] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:11:18,212] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:18,226] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.857 seconds
[2022-08-09 08:11:48,475] {processor.py:163} INFO - Started process (PID=976) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:48,476] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:11:48,477] {logging_mixin.py:109} INFO - [2022-08-09 08:11:48,477] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:49,140] {logging_mixin.py:109} INFO - [2022-08-09 08:11:49,138] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:11:49,157] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:11:49,165] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.695 seconds
[2022-08-09 08:12:19,293] {processor.py:163} INFO - Started process (PID=1047) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:19,295] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:12:19,296] {logging_mixin.py:109} INFO - [2022-08-09 08:12:19,296] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:19,948] {logging_mixin.py:109} INFO - [2022-08-09 08:12:19,946] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:12:19,965] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:19,974] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.685 seconds
[2022-08-09 08:12:50,202] {processor.py:163} INFO - Started process (PID=1108) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:50,205] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:12:50,207] {logging_mixin.py:109} INFO - [2022-08-09 08:12:50,207] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:51,043] {logging_mixin.py:109} INFO - [2022-08-09 08:12:51,040] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:12:51,058] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:12:51,080] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.883 seconds
[2022-08-09 08:13:21,189] {processor.py:163} INFO - Started process (PID=1181) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:21,191] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:13:21,192] {logging_mixin.py:109} INFO - [2022-08-09 08:13:21,192] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:21,969] {logging_mixin.py:109} INFO - [2022-08-09 08:13:21,967] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:13:21,992] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:22,005] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.819 seconds
[2022-08-09 08:13:52,117] {processor.py:163} INFO - Started process (PID=1246) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:52,119] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:13:52,121] {logging_mixin.py:109} INFO - [2022-08-09 08:13:52,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:52,786] {logging_mixin.py:109} INFO - [2022-08-09 08:13:52,783] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:13:52,801] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:13:52,811] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.697 seconds
[2022-08-09 08:14:23,360] {processor.py:163} INFO - Started process (PID=1314) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:23,362] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:14:23,364] {logging_mixin.py:109} INFO - [2022-08-09 08:14:23,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:24,057] {logging_mixin.py:109} INFO - [2022-08-09 08:14:24,056] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:14:24,078] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:24,088] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.731 seconds
[2022-08-09 08:14:54,152] {processor.py:163} INFO - Started process (PID=1376) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:54,154] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:14:54,156] {logging_mixin.py:109} INFO - [2022-08-09 08:14:54,156] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:55,031] {logging_mixin.py:109} INFO - [2022-08-09 08:14:55,028] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:14:55,047] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:14:55,059] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.911 seconds
[2022-08-09 08:15:25,158] {processor.py:163} INFO - Started process (PID=1450) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:25,162] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:15:25,164] {logging_mixin.py:109} INFO - [2022-08-09 08:15:25,163] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:25,851] {logging_mixin.py:109} INFO - [2022-08-09 08:15:25,849] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:15:25,870] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:25,882] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.728 seconds
[2022-08-09 08:15:56,458] {processor.py:163} INFO - Started process (PID=1511) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:56,461] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:15:56,462] {logging_mixin.py:109} INFO - [2022-08-09 08:15:56,462] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:57,140] {logging_mixin.py:109} INFO - [2022-08-09 08:15:57,137] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:15:57,155] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:15:57,167] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.714 seconds
[2022-08-09 08:16:27,670] {processor.py:163} INFO - Started process (PID=1579) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:27,673] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:16:27,674] {logging_mixin.py:109} INFO - [2022-08-09 08:16:27,674] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:28,358] {logging_mixin.py:109} INFO - [2022-08-09 08:16:28,355] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:16:28,384] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:28,398] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.731 seconds
[2022-08-09 08:16:58,773] {processor.py:163} INFO - Started process (PID=1639) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:58,775] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:16:58,777] {logging_mixin.py:109} INFO - [2022-08-09 08:16:58,777] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:59,389] {logging_mixin.py:109} INFO - [2022-08-09 08:16:59,387] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:16:59,405] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:16:59,413] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.646 seconds
[2022-08-09 08:17:29,682] {processor.py:163} INFO - Started process (PID=1708) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:17:29,683] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:17:29,685] {logging_mixin.py:109} INFO - [2022-08-09 08:17:29,685] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:17:30,349] {logging_mixin.py:109} INFO - [2022-08-09 08:17:30,347] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:17:30,365] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:17:30,375] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.697 seconds
[2022-08-09 08:18:00,465] {processor.py:163} INFO - Started process (PID=1768) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:00,468] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:18:00,470] {logging_mixin.py:109} INFO - [2022-08-09 08:18:00,470] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:01,078] {logging_mixin.py:109} INFO - [2022-08-09 08:18:01,076] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:18:01,093] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:01,102] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.642 seconds
[2022-08-09 08:18:31,344] {processor.py:163} INFO - Started process (PID=1837) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:31,346] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:18:31,347] {logging_mixin.py:109} INFO - [2022-08-09 08:18:31,347] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:32,013] {logging_mixin.py:109} INFO - [2022-08-09 08:18:32,011] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:18:32,035] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:18:32,043] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.702 seconds
[2022-08-09 08:19:02,785] {processor.py:163} INFO - Started process (PID=1898) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:02,788] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:19:02,789] {logging_mixin.py:109} INFO - [2022-08-09 08:19:02,789] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:03,467] {logging_mixin.py:109} INFO - [2022-08-09 08:19:03,466] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:19:03,485] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:03,497] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.715 seconds
[2022-08-09 08:19:33,642] {processor.py:163} INFO - Started process (PID=1967) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:33,644] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:19:33,645] {logging_mixin.py:109} INFO - [2022-08-09 08:19:33,645] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:34,252] {logging_mixin.py:109} INFO - [2022-08-09 08:19:34,250] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:19:34,267] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:19:34,275] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.636 seconds
[2022-08-09 08:20:04,370] {processor.py:163} INFO - Started process (PID=2027) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:04,371] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:20:04,373] {logging_mixin.py:109} INFO - [2022-08-09 08:20:04,373] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:04,999] {logging_mixin.py:109} INFO - [2022-08-09 08:20:04,997] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:20:05,018] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:05,027] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.660 seconds
[2022-08-09 08:20:35,694] {processor.py:163} INFO - Started process (PID=2096) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:35,697] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:20:35,699] {logging_mixin.py:109} INFO - [2022-08-09 08:20:35,699] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:36,327] {logging_mixin.py:109} INFO - [2022-08-09 08:20:36,325] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:20:36,347] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:20:36,355] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.666 seconds
[2022-08-09 08:21:06,531] {processor.py:163} INFO - Started process (PID=2157) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:06,534] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:21:06,536] {logging_mixin.py:109} INFO - [2022-08-09 08:21:06,536] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:07,151] {logging_mixin.py:109} INFO - [2022-08-09 08:21:07,148] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:21:07,167] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:07,177] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.651 seconds
[2022-08-09 08:21:37,731] {processor.py:163} INFO - Started process (PID=2227) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:37,734] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:21:37,736] {logging_mixin.py:109} INFO - [2022-08-09 08:21:37,736] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:38,413] {logging_mixin.py:109} INFO - [2022-08-09 08:21:38,411] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:21:38,431] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:21:38,443] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.717 seconds
[2022-08-09 08:22:08,867] {processor.py:163} INFO - Started process (PID=2286) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:08,870] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:22:08,872] {logging_mixin.py:109} INFO - [2022-08-09 08:22:08,872] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:09,491] {logging_mixin.py:109} INFO - [2022-08-09 08:22:09,488] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:22:09,505] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:09,514] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.652 seconds
[2022-08-09 08:22:39,567] {processor.py:163} INFO - Started process (PID=2355) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:39,570] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:22:39,572] {logging_mixin.py:109} INFO - [2022-08-09 08:22:39,571] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:40,216] {logging_mixin.py:109} INFO - [2022-08-09 08:22:40,214] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:22:40,231] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:22:40,244] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.680 seconds
[2022-08-09 08:23:10,389] {processor.py:163} INFO - Started process (PID=2416) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:10,393] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:23:10,395] {logging_mixin.py:109} INFO - [2022-08-09 08:23:10,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:10,976] {logging_mixin.py:109} INFO - [2022-08-09 08:23:10,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:23:10,992] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:11,000] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.616 seconds
[2022-08-09 08:23:41,595] {processor.py:163} INFO - Started process (PID=2486) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:41,597] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:23:41,599] {logging_mixin.py:109} INFO - [2022-08-09 08:23:41,599] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:42,169] {logging_mixin.py:109} INFO - [2022-08-09 08:23:42,166] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:23:42,187] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:23:42,238] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.649 seconds
[2022-08-09 08:24:12,877] {processor.py:163} INFO - Started process (PID=2546) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:12,880] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:24:12,883] {logging_mixin.py:109} INFO - [2022-08-09 08:24:12,883] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:13,445] {logging_mixin.py:109} INFO - [2022-08-09 08:24:13,443] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:24:13,461] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:13,472] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.599 seconds
[2022-08-09 08:24:43,714] {processor.py:163} INFO - Started process (PID=2617) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:43,716] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:24:43,718] {logging_mixin.py:109} INFO - [2022-08-09 08:24:43,718] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:44,337] {logging_mixin.py:109} INFO - [2022-08-09 08:24:44,335] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:24:44,353] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:24:44,361] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.651 seconds
[2022-08-09 08:25:14,590] {processor.py:163} INFO - Started process (PID=2677) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:14,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:25:14,593] {logging_mixin.py:109} INFO - [2022-08-09 08:25:14,593] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:15,174] {logging_mixin.py:109} INFO - [2022-08-09 08:25:15,172] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:25:15,189] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:15,199] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.636 seconds
[2022-08-09 08:25:45,931] {processor.py:163} INFO - Started process (PID=2747) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:45,934] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:25:45,935] {logging_mixin.py:109} INFO - [2022-08-09 08:25:45,935] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:46,528] {logging_mixin.py:109} INFO - [2022-08-09 08:25:46,525] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:25:46,542] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:25:46,550] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.625 seconds
[2022-08-09 08:26:17,331] {processor.py:163} INFO - Started process (PID=2807) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:17,333] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:26:17,335] {logging_mixin.py:109} INFO - [2022-08-09 08:26:17,335] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:17,944] {logging_mixin.py:109} INFO - [2022-08-09 08:26:17,942] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:26:17,962] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:17,973] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.647 seconds
[2022-08-09 08:26:48,842] {processor.py:163} INFO - Started process (PID=2877) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:48,847] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:26:48,849] {logging_mixin.py:109} INFO - [2022-08-09 08:26:48,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:49,443] {logging_mixin.py:109} INFO - [2022-08-09 08:26:49,440] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:26:49,460] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:26:49,468] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.634 seconds
[2022-08-09 08:27:20,320] {processor.py:163} INFO - Started process (PID=2937) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:20,323] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:27:20,325] {logging_mixin.py:109} INFO - [2022-08-09 08:27:20,325] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:20,895] {logging_mixin.py:109} INFO - [2022-08-09 08:27:20,893] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:27:20,913] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:20,923] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.608 seconds
[2022-08-09 08:27:51,619] {processor.py:163} INFO - Started process (PID=3007) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:51,621] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:27:51,623] {logging_mixin.py:109} INFO - [2022-08-09 08:27:51,622] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:52,243] {logging_mixin.py:109} INFO - [2022-08-09 08:27:52,241] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:27:52,261] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:27:52,272] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.658 seconds
[2022-08-09 08:28:22,733] {processor.py:163} INFO - Started process (PID=3067) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:22,736] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:28:22,739] {logging_mixin.py:109} INFO - [2022-08-09 08:28:22,739] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:23,310] {logging_mixin.py:109} INFO - [2022-08-09 08:28:23,308] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:28:23,325] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:23,333] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.608 seconds
[2022-08-09 08:28:53,508] {processor.py:163} INFO - Started process (PID=3136) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:53,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:28:53,513] {logging_mixin.py:109} INFO - [2022-08-09 08:28:53,513] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:54,119] {logging_mixin.py:109} INFO - [2022-08-09 08:28:54,117] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:28:54,133] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:28:54,144] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.640 seconds
[2022-08-09 08:29:25,003] {processor.py:163} INFO - Started process (PID=3196) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:25,007] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:29:25,010] {logging_mixin.py:109} INFO - [2022-08-09 08:29:25,010] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:25,574] {logging_mixin.py:109} INFO - [2022-08-09 08:29:25,572] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:29:25,590] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:25,600] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.600 seconds
[2022-08-09 08:29:56,558] {processor.py:163} INFO - Started process (PID=3265) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:56,562] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:29:56,564] {logging_mixin.py:109} INFO - [2022-08-09 08:29:56,564] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:57,208] {logging_mixin.py:109} INFO - [2022-08-09 08:29:57,204] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:29:57,265] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:29:57,280] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.727 seconds
[2022-08-09 08:30:27,951] {processor.py:163} INFO - Started process (PID=3325) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:30:27,955] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:30:27,957] {logging_mixin.py:109} INFO - [2022-08-09 08:30:27,957] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:30:28,567] {logging_mixin.py:109} INFO - [2022-08-09 08:30:28,565] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:30:28,582] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:30:28,591] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.644 seconds
[2022-08-09 08:30:59,542] {processor.py:163} INFO - Started process (PID=3395) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:30:59,545] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:30:59,546] {logging_mixin.py:109} INFO - [2022-08-09 08:30:59,546] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:31:00,134] {logging_mixin.py:109} INFO - [2022-08-09 08:31:00,132] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:31:00,149] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:31:00,161] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.624 seconds
[2022-08-09 08:31:30,831] {processor.py:163} INFO - Started process (PID=3464) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:31:30,833] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:31:30,834] {logging_mixin.py:109} INFO - [2022-08-09 08:31:30,834] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:31:31,467] {logging_mixin.py:109} INFO - [2022-08-09 08:31:31,464] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:31:31,482] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:31:31,491] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.664 seconds
[2022-08-09 08:32:02,015] {processor.py:163} INFO - Started process (PID=3527) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:02,017] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:32:02,019] {logging_mixin.py:109} INFO - [2022-08-09 08:32:02,019] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:02,685] {logging_mixin.py:109} INFO - [2022-08-09 08:32:02,682] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:32:02,701] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:02,710] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.700 seconds
[2022-08-09 08:32:33,387] {processor.py:163} INFO - Started process (PID=3599) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:33,389] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:32:33,391] {logging_mixin.py:109} INFO - [2022-08-09 08:32:33,390] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:34,036] {logging_mixin.py:109} INFO - [2022-08-09 08:32:34,034] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:32:34,051] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:32:34,061] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.677 seconds
[2022-08-09 08:33:04,167] {processor.py:163} INFO - Started process (PID=3664) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:04,170] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:33:04,171] {logging_mixin.py:109} INFO - [2022-08-09 08:33:04,171] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:04,746] {logging_mixin.py:109} INFO - [2022-08-09 08:33:04,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:33:04,760] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:04,769] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.605 seconds
[2022-08-09 08:33:35,243] {processor.py:163} INFO - Started process (PID=3735) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:35,246] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:33:35,247] {logging_mixin.py:109} INFO - [2022-08-09 08:33:35,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:35,873] {logging_mixin.py:109} INFO - [2022-08-09 08:33:35,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:33:35,891] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:33:35,901] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.664 seconds
[2022-08-09 08:34:05,974] {processor.py:163} INFO - Started process (PID=3795) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:05,978] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:34:05,979] {logging_mixin.py:109} INFO - [2022-08-09 08:34:05,979] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:06,595] {logging_mixin.py:109} INFO - [2022-08-09 08:34:06,592] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:34:06,611] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:06,622] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.652 seconds
[2022-08-09 08:34:37,421] {processor.py:163} INFO - Started process (PID=3865) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:37,424] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:34:37,428] {logging_mixin.py:109} INFO - [2022-08-09 08:34:37,428] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:38,089] {logging_mixin.py:109} INFO - [2022-08-09 08:34:38,086] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:34:38,110] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:34:38,121] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.705 seconds
[2022-08-09 08:35:08,824] {processor.py:163} INFO - Started process (PID=3925) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:08,829] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:35:08,832] {logging_mixin.py:109} INFO - [2022-08-09 08:35:08,831] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:09,392] {logging_mixin.py:109} INFO - [2022-08-09 08:35:09,389] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:35:09,409] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:09,419] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.604 seconds
[2022-08-09 08:35:39,560] {processor.py:163} INFO - Started process (PID=3994) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:39,564] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:35:39,566] {logging_mixin.py:109} INFO - [2022-08-09 08:35:39,566] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:40,557] {logging_mixin.py:109} INFO - [2022-08-09 08:35:40,554] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:35:40,581] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:35:40,601] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1.046 seconds
[2022-08-09 08:36:11,129] {processor.py:163} INFO - Started process (PID=4054) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:11,133] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:36:11,135] {logging_mixin.py:109} INFO - [2022-08-09 08:36:11,135] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:12,258] {logging_mixin.py:109} INFO - [2022-08-09 08:36:12,253] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:36:12,304] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:12,331] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1.210 seconds
[2022-08-09 08:36:42,553] {processor.py:163} INFO - Started process (PID=4118) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:42,557] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:36:42,560] {logging_mixin.py:109} INFO - [2022-08-09 08:36:42,560] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:43,709] {logging_mixin.py:109} INFO - [2022-08-09 08:36:43,703] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:36:43,742] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:36:43,760] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1.219 seconds
[2022-08-09 08:55:22,543] {processor.py:163} INFO - Started process (PID=4164) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:55:22,563] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-09 08:55:22,573] {logging_mixin.py:109} INFO - [2022-08-09 08:55:22,572] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:55:25,714] {logging_mixin.py:109} INFO - [2022-08-09 08:55:25,711] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-09 08:55:25,762] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-09 08:55:25,806] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 3.281 seconds
